# Generated by Django 4.1.7 on 2023-03-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_Name', models.CharField(max_length=50)),
                ('Admin_Designation', models.CharField(max_length=50)),
                ('Admin_Password', models.CharField(max_length=50)),
                ('Phone', models.IntegerField()),
            ],
        ),
    ]
