# Generated by Django 4.1.7 on 2023-04-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Teacher_Qualification',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
